server:
  port: 8097

spring:
  application:
    name: admin-server
  boot:
    admin:
      server:
        enabled: true

management:
  endpoints:
      web:
        cors:
          allowed-methods: '*'
  endpoint:
    health:
      show-details: always


