spring:
  application:
    name: minio-demo
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB

server:
  port: 8037

minio:
  endpoint: http://172.30.233.158:9000      # MinIO服务地址
  fileHost: http://172.30.233.158:9000     # 文件地址host
#  endpoint: http://192.168.3.39:9000      # MinIO服务地址
#  fileHost: http://192.168.3.39:9000     # 文件地址host
  bucketName: my-bucket                     # 存储桶bucket名称
  accessKey: admin                         # 用户名
  secretKey: admin123456                     # 密码
