server:
  port: 8096

spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        #admin客户端密码必须要配置否则访问不到server端 security.user name/password 可以不用配置
        password: '123456'
        username: 'admin'
        url: 'http://localhost:8095'
  security:
    user:
      name: 'admin'
      password: '123456'

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"




