server:
  port: 8089
  servlet:
    context-path: /api

spring:
  application:
    name: spring-boot-aop

logging:
  level:
    root: INFO
    com:
      shenlx:
        xinwen:
          springbootaop: DEBUG
  file:
    name: log
    path: D:/logs/springboot-aop
