server:
  port: 8087
  servlet:
    context-path: /api

spring:
  application:
    name: spring-boot-jdbc-template
    # \u6570\u636E\u5E93\u8BBF\u95EE\u914D\u7F6E, \u4F7F\u7528druid\u6570\u636E\u6E90
  datasource:
    url: jdbc:mysql://172.18.51.90:3310/auth_dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    # url: jdbc:mysql://172.27.52.37:3306/sd_dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Neusoft@123
    # password: admin@2023
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #\u8FDE\u63A5\u6C60\u914D\u7F6E
      initial-size: 5
      min-idle: 5
      max-active: 20
      #\u8FDE\u63A5\u7B49\u5F85\u65F6\u95F4
      max-wait: 30000
      # \u914D\u7F6E\u68C0\u6D4B\u53EF\u4EE5\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\u95F4\u9694\u65F6\u95F4
      time-between-eviction-runs-millis: 60000
      # \u914D\u7F6E\u8FDE\u63A5\u5728\u6C60\u4E2D\u7684\u6700\u5C0F\u751F\u5B58\u65F6\u95F4
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # \u6253\u5F00PSCache\uFF0C\u5E76\u4E14\u6307\u5B9A\u6BCF\u4E2A\u8FDE\u63A5\u4E0APSCache\u7684\u5927\u5C0F
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20


